# Global Superstore

The Global Superstore dataset is a popular sample dataset often used for data analysis and visualization exercises. It generally includes the following key fields:

Order ID: Unique identifier for each order.

Order Date: Date when the order was placed.

Ship Date: Date when the order was shipped.

Ship Mode: The shipping method used (e.g., Standard Class, Second Class, etc.).

Customer ID: Unique identifier for each customer.

Customer Name: Name of the customer.

Segment: Customer segment (e.g., Consumer, Corporate, Home Office).

Country: Country where the customer is located.

City: City where the customer is located.

State: State where the customer is located.

Postal Code: Postal code of the customer's address.

Category: Product category (e.g., Furniture, Office Supplies, Technology).

Sub-Category: More specific category within the broader category.

Product Name: Name of the product.

Sales: Sales amount for the order.

Quantity: Quantity of products ordered.

Discount: Discount applied to the order.

Profit: Profit made on the order.

This dataset is used to analyze sales performance, customer behavior, and other

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.read_excel('global_superstore.xlsx')

In [ ]:
data

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,221.980,2,0.0,62.1544,40.770,High
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.630,Critical
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.490,Medium
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.160,Medium
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.040,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2015-KE1642066-42174,2015-06-19,2015-06-19,Same Day,KE-1642066,Katrina Edelman,Corporate,NaN,Kure,...,OFF-FA-3072,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,1.010,Medium
51286,34337,US-2014-ZD21925140-41765,2014-05-06,2014-05-10,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,FUR-FU-4070,Furniture,Furnishings,"Eldon Image Series Desk Accessories, Burgundy",16.720,5,0.2,3.3440,1.930,High
51287,31315,CA-2012-ZD21925140-41147,2012-08-26,2012-08-31,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,OFF-AR-5321,Office Supplies,Art,Newell 341,8.560,2,0.0,2.4824,1.580,High
51288,9596,MX-2013-RB1979518-41322,2013-02-17,2013-02-21,Standard Class,RB-1979518,Ross Baird,Home Office,NaN,Valinhos,...,OFF-BI-2919,Office Supplies,Binders,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,1.003,Medium
51289,6147,MX-2013-MC1810093-41416,2013-05-22,2013-05-26,Second Class,MC-1810093,Mick Crebagga,Consumer,NaN,Tipitapa,...,OFF-PA-3990,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,1.002,High

In [ ]:
data.shape

(51290, 24)

In [ ]:
data.size

1230960

In [ ]:
data.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,221.980,2,0.0,62.1544,40.77,High
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical
5,22732,IN-2014-JM156557-41818,2014-06-28,2014-07-01,Second Class,JM-156557,Jim Mitchum,Corporate,NaN,Sydney,...,TEC-PH-5842,Technology,Phones,"Samsung Smart Phone, with Caller ID",2862.675,5,0.1,763.2750,897.35,Critical
6,30570,IN-2012-TS2134092-41219,2012-11-06,2012-11-08,First Class,TS-2134092,Toby Swindell,Consumer,NaN,Porirua,...,FUR-CH-5378,Furniture,Chairs,"Novimex Executive Leather Armchair, Adjustable",1822.080,4,0.0,564.8400,894.77,Critical
7,31192,IN-2013-MB1808592-41378,2013-04-14,2013-04-18,Standard Class,MB-1808592,Mick Brown,Consumer,NaN,Hamilton,...,FUR-TA-3764,Furniture,Tables,"Chromcraft Conference Table, Fully Assembled",5244.840,6,0.0,996.4800,878.38,High
8,40099,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,FUR-BO-5957,Furniture,Bookcases,"Sauder Facets Collection Library, Sky Alder Fi...",341.960,2,0.0,54.7136,25.27,High
9,36258,CA-2012-AB10015140-40974,2012-03-06,2012-03-07,First Class,AB-100151404,Aaron Bergman,Consumer,98103.0,Seattle,...,FUR-CH-4421,Furniture,Chairs,"Global Push Button Manager's Chair, Indigo",48.712,1,0.2,5.4801,11.13,High

In [ ]:
data.tail(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
51280,35112,CA-2014-ZD21925140-41829,2014-07-09,2014-07-09,Same Day,ZD-219251408,Zuschuss Donatelli,Consumer,32216.0,Jacksonville,...,OFF-PA-6474,Office Supplies,Paper,Xerox 1921,15.984,2,0.2,4.9950,2.010,Medium
51281,6039,MX-2015-HG1502518-42164,2015-06-09,2015-06-11,First Class,HG-1502518,Hunter Glantz,Consumer,NaN,Bragança Paulista,...,OFF-PA-4475,Office Supplies,Paper,"Green Bar Message Books, Multicolor",84.000,5,0.0,9.2000,1.019,High
51282,24175,IN-2015-DB132707-42221,2015-08-05,2015-08-10,Standard Class,DB-132707,Deborah Brumfield,Home Office,NaN,Townsville,...,OFF-BI-3253,Office Supplies,Binders,"Avery Binder, Economy",58.050,5,0.1,19.9500,1.010,Medium
51283,24105,IN-2015-KH1633058-42154,2015-05-30,2015-05-30,Same Day,KH-1633058,Katharine Harms,Corporate,NaN,Lucknow,...,OFF-PA-4007,Office Supplies,Paper,"Eaton Parchment Paper, Premium",26.940,2,0.0,1.8600,1.010,High
51284,9922,MX-2013-KM1637593-41636,2013-12-28,2013-12-31,First Class,KM-1637593,Katherine Murray,Home Office,NaN,Managua,...,OFF-PA-5876,Office Supplies,Paper,"SanDisk Message Books, 8.5 x 11",18.640,1,0.0,8.0000,1.010,Medium
51285,29002,IN-2015-KE1642066-42174,2015-06-19,2015-06-19,Same Day,KE-1642066,Katrina Edelman,Corporate,NaN,Kure,...,OFF-FA-3072,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,1.010,Medium
51286,34337,US-2014-ZD21925140-41765,2014-05-06,2014-05-10,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,FUR-FU-4070,Furniture,Furnishings,"Eldon Image Series Desk Accessories, Burgundy",16.720,5,0.2,3.3440,1.930,High
51287,31315,CA-2012-ZD21925140-41147,2012-08-26,2012-08-31,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,OFF-AR-5321,Office Supplies,Art,Newell 341,8.560,2,0.0,2.4824,1.580,High
51288,9596,MX-2013-RB1979518-41322,2013-02-17,2013-02-21,Standard Class,RB-1979518,Ross Baird,Home Office,NaN,Valinhos,...,OFF-BI-2919,Office Supplies,Binders,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,1.003,Medium
51289,6147,MX-2013-MC1810093-41416,2013-05-22,2013-05-26,Second Class,MC-1810093,Mick Crebagga,Consumer,NaN,Tipitapa,...,OFF-PA-3990,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,1.002,High

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  object
 2   Order Date      51290 non-null  datetime64[ns]
 3   Ship Date       51290 non-null  datetime64[ns]
 4   Ship Mode       51290 non-null  object
 5   Customer ID     51290 non-null  object
 6   Customer Name   51290 non-null  object
 7   Segment         51290 non-null  object
 8   Postal Code     9994 non-null   float64
 9   City            51290 non-null  object
 10  State           51290 non-null  object
 11  Country         51290 non-null  object
 12  Region          51290 non-null  object
 13  Market          51290 non-null  object
 14  Product ID      51290 non-null  object
 15  Category        51290 non-null  object
 16  Sub-Category    51290 non-null  object
 17  Product Name    51290 non-null  object
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  object
dtypes: datetime64[ns](2), float64(5), int64(2), object(15)
memory usage: 9.4+ MB

In [ ]:
data.describe().T
# .T - used to transpose

,count,mean,min,25%,50%,75%,max,std
Row ID,51290.0,25645.5,1.0,12823.25,25645.5,38467.75,51290.0,14806.29199
Order Date,51290,2014-05-11 21:26:49.155780608,2012-01-01 00:00:00,2013-06-19 00:00:00,2014-07-08 00:00:00,2015-05-22 00:00:00,2015-12-31 00:00:00,NaN
Ship Date,51290,2014-05-15 20:42:42.745174528,2012-01-03 00:00:00,2013-06-23 00:00:00,2014-07-12 00:00:00,2015-05-26 00:00:00,2016-01-07 00:00:00,NaN
Postal Code,9994.0,55190.379428,1040.0,23223.0,56430.5,90008.0,99301.0,32063.69335
Sales,51290.0,246.490581,0.444,30.758625,85.053,251.0532,22638.48,487.565361
Quantity,51290.0,3.476545,1.0,2.0,3.0,5.0,14.0,2.278766
Discount,51290.0,0.142908,0.0,0.0,0.0,0.2,0.85,0.21228
Profit,51290.0,28.610982,-6599.978,0.0,9.24,36.81,8399.976,174.340972
Shipping Cost,51290.0,26.478567,1.002,2.61,7.79,24.45,933.57,57.251373

In [ ]:
data.describe(include='all')

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
count,51290.00000,51290,51290,51290,51290,51290,51290,51290,9994.000000,51290,...,51290,51290,51290,51290,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290
unique,NaN,25728,NaN,NaN,4,17415,796,3,NaN,3650,...,3788,3,17,3788,NaN,NaN,NaN,NaN,NaN,4
top,NaN,CA-2015-SV20365140-42268,NaN,NaN,Standard Class,SV-203651406,Muhammed Yedwab,Consumer,NaN,New York City,...,OFF-FA-6129,Office Supplies,Binders,Staples,NaN,NaN,NaN,NaN,NaN,Medium
freq,NaN,14,NaN,NaN,30775,26,108,26518,NaN,915,...,227,31289,6146,227,NaN,NaN,NaN,NaN,NaN,29433
mean,25645.50000,NaN,2014-05-11 21:26:49.155780608,2014-05-15 20:42:42.745174528,NaN,NaN,NaN,NaN,55190.379428,NaN,...,NaN,NaN,NaN,NaN,246.490581,3.476545,0.142908,28.610982,26.478567,NaN
min,1.00000,NaN,2012-01-01 00:00:00,2012-01-03 00:00:00,NaN,NaN,NaN,NaN,1040.000000,NaN,...,NaN,NaN,NaN,NaN,0.444000,1.000000,0.000000,-6599.978000,1.002000,NaN
25%,12823.25000,NaN,2013-06-19 00:00:00,2013-06-23 00:00:00,NaN,NaN,NaN,NaN,23223.000000,NaN,...,NaN,NaN,NaN,NaN,30.758625,2.000000,0.000000,0.000000,2.610000,NaN
50%,25645.50000,NaN,2014-07-08 00:00:00,2014-07-12 00:00:00,NaN,NaN,NaN,NaN,56430.500000,NaN,...,NaN,NaN,NaN,NaN,85.053000,3.000000,0.000000,9.240000,7.790000,NaN
75%,38467.75000,NaN,2015-05-22 00:00:00,2015-05-26 00:00:00,NaN,NaN,NaN,NaN,90008.000000,NaN,...,NaN,NaN,NaN,NaN,251.053200,5.000000,0.200000,36.810000,24.450000,NaN
max,51290.00000,NaN,2015-12-31 00:00:00,2016-01-07 00:00:00,NaN,NaN,NaN,NaN,99301.000000,NaN,...,NaN,NaN,NaN,NaN,22638.480000,14.000000,0.850000,8399.976000,933.570000,NaN
std,14806.29199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32063.693350,NaN,...,NaN,NaN,NaN,NaN,487.565361,2.278766,0.212280,174.340972,57.251373,NaN

In [ ]:
data.describe(include='object')

,Order ID,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,Region,Market,Product ID,Category,Sub-Category,Product Name,Order Priority
count,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290
unique,25728,4,17415,796,3,3650,1102,165,23,5,3788,3,17,3788,4
top,CA-2015-SV20365140-42268,Standard Class,SV-203651406,Muhammed Yedwab,Consumer,New York City,California,United States,Western Europe,Asia Pacific,OFF-FA-6129,Office Supplies,Binders,Staples,Medium
freq,14,30775,26,108,26518,915,2001,9994,5883,14302,227,31289,6146,227,29433

In [ ]:
data.ndim

2

In [ ]:
data.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Postal Code', 'City',
       'State', 'Country', 'Region', 'Market', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority'],
      dtype='object')

In [ ]:
data.nunique()

Row ID            51290
Order ID          25728
Order Date         1430
Ship Date          1464
Ship Mode             4
Customer ID       17415
Customer Name       796
Segment               3
Postal Code         631
City               3650
State              1102
Country             165
Region               23
Market                5
Product ID         3788
Category              3
Sub-Category         17
Product Name       3788
Sales             27200
Quantity             14
Discount             29
Profit            28234
Shipping Cost     16753
Order Priority        4
dtype: int64

In [ ]:
data.isnull().sum()

Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
Postal Code       41296
City                  0
State                 0
Country               0
Region                0
Market                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

In [ ]:
data.value_counts()

Row ID  Order ID                  Order Date  Ship Date   Ship Mode       Customer ID   Customer Name     Segment      Postal Code  City         State          Country        Region       Market  Product ID   Category         Sub-Category  Product Name                                                               Sales    Quantity  Discount  Profit     Shipping Cost  Order Priority
31297   CA-2014-CG12520140-41952  2014-11-09  2014-11-12  Second Class    CG-125201408  Claire Gute       Consumer     42420.0      Henderson    Kentucky       United States  Southern US  USCA    FUR-BO-3645  Furniture        Bookcases     Bush Somerset Collection Bookcase                                          261.960  2         0.0        41.9136   54.10          Critical          1
37962   CA-2014-JS15880140-41835  2014-07-15  2014-07-19  Second Class    JS-158801402  John Stevenson    Consumer     75061.0      Irving       Texas          United States  Central US   USCA    OFF-PA-6466  Office Supplies  Paper         Xerox 1914                                                                 219.840  5         0.2        79.6920   35.96          High              1
37955   CA-2015-KM16375140-42056  2015-02-21  2015-02-28  Standard Class  KM-163751404  Katherine Murray  Home Office  85234.0      Gilbert      Arizona        United States  Western US   USCA    FUR-FU-4759  Furniture        Furnishings   Howard Miller 13" Diameter Pewter Finish Round Wall Clock                  68.704   2         0.2        16.3172   7.59           Low               1
37956   CA-2015-KM16375140-42056  2015-02-21  2015-02-28  Standard Class  KM-163751404  Katherine Murray  Home Office  85234.0      Gilbert      Arizona        United States  Western US   USCA    FUR-TA-4943  Furniture        Tables        KI Adjustable-Height Table                                                 386.910  9         0.5       -185.7168  44.06          Low               1
37957   CA-2013-DB13405140-41494  2013-08-08  2013-08-10  Second Class    DB-134051406  Denny Blanton     Consumer     1841.0       Lawrence     Massachusetts  United States  Eastern US   USCA    OFF-AR-3522  Office Supplies  Art           Boston 1827 Commercial Additional Cutter, Drive Gear & Gear Rack for 1606  39.660   2         0.0        11.8980   8.62           Critical          1
                                                                                                                                                                                                                                                                                                                                                                                                   ..
34629   CA-2015-GM14455140-42353  2015-12-15  2015-12-21  Standard Class  GM-144551402  Gary Mitchum      Home Office  60653.0      Chicago      Illinois       United States  Central US   USCA    TEC-PH-5828  Technology       Phones        Samsung HM1900 Bluetooth Headset                                           52.680   3         0.2        19.7550   1.36           Medium            1
34630   CA-2015-GM14455140-42353  2015-12-15  2015-12-21  Standard Class  GM-144551402  Gary Mitchum      Home Office  60653.0      Chicago      Illinois       United States  Central US   USCA    FUR-FU-5172  Furniture        Furnishings   Master Caster Door Stop, Gray                                              2.032    1         0.6       -1.3208    1.10           Medium            1
34631   US-2015-PR18880140-42238  2015-08-22  2015-08-23  First Class     PR-188801404  Patrick Ryan      Consumer     94601.0      Oakland      California     United States  Western US   USCA    OFF-AR-5315  Office Supplies  Art           Newell 336                                                                 17.120   4         0.0        4.9648    2.36           Medium            1
34632   US-2015-PR18880140-42238  2015-08-22  2015-08-23  First Class     PR-188801404  Patrick Ryan      Consumer     94601.0      Oakland      California     United States  Western US   USCA    TEC-PH-3782  Technology       Phones        Cisco 8x8 Inc. 6753i IP Business Phone System                              431.968  4         0.2        37.7972   37.76          Medium            1
41290   CA-2015-CC12220140-42129  2015-05-05  2015-05-10  Second Class    CC-122201404  Chris Cortes      Consumer     92683.0      Westminster  California     United States  Western US   USCA    OFF-AP-2889  Office Supplies  Appliances    Acco 7-Outlet Masterpiece Power Center, Wihtout Fax/Phone Line Protection  243.160  2         0.0        72.9480   25.33          Medium            1
Name: count, Length: 9994, dtype: int64

In [ ]:
data.dtypes

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Postal Code              float64
City                      object
State                     object
Country                   object
Region                    object
Market                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
Shipping Cost            float64
Order Priority            object
dtype: object

## **checking duplicates**

In [ ]:
data.duplicated()
# to check duplicate values, display boolean

0        False
1        False
2        False
3        False
4        False
         ...
51285    False
51286    False
51287    False
51288    False
51289    False
Length: 51290, dtype: bool

In [ ]:
data.duplicated().sum()
# display duplicated number counts

0

In [ ]:
data.duplicated(subset=['Customer ID','Product ID']).sum()
# to display specific column duplicated numbers

118

In [ ]:
df1=data[data.duplicated(subset=['Customer ID','Product ID'])]
# store to a new variable specific column duplicates and display

In [ ]:
df1

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
143,31649,CA-2014-AB10060140-41884,2014-09-02,2014-09-04,First Class,AB-100601406,Adam Bellavance,Home Office,10009.0,New York City,...,OFF-PA-6430,Office Supplies,Paper,Xerox 1881,49.120,4,0.0,23.0864,6.220,Critical
2628,40081,US-2015-AS10630140-42081,2015-03-18,2015-03-24,Standard Class,AS-106301408,Ann Steele,Home Office,37918.0,Knoxville,...,OFF-LA-3192,Office Supplies,Labels,Avery 474,4.608,2,0.2,1.6704,1.220,Medium
4257,33490,CA-2014-AP10915140-41984,2014-12-11,2014-12-18,Standard Class,AP-109151404,Arthur Prichep,Consumer,98105.0,Seattle,...,OFF-PA-6546,Office Supplies,Paper,Xerox 1988,123.920,4,0.0,55.7640,12.440,Low
4892,10287,US-2014-DN1369018-41688,2014-02-18,2014-02-22,Standard Class,DN-1369018,Duane Noonan,Consumer,NaN,Açu,...,FUR-TA-4645,Furniture,Tables,"Hon Conference Table, Adjustable Height",985.248,4,0.6,-936.0320,67.853,High
5091,2377,MX-2013-AG1090082-41398,2013-05-04,2013-05-09,Standard Class,AG-1090082,Arthur Gainer,Consumer,NaN,Mexico City,...,OFF-AP-4508,Office Supplies,Appliances,"Hamilton Beach Stove, White",720.640,2,0.0,72.0400,65.580,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50428,10001,US-2014-DP1300018-41909,2014-09-27,2014-10-01,Standard Class,DP-1300018,Darren Powers,Consumer,NaN,Araranguá,...,OFF-EN-4446,Office Supplies,Envelopes,"GlobeWeis Mailers, with clear poly window",22.448,2,0.6,-12.3520,1.151,Medium
50611,11,MX-2014-DP1300018-41909,2014-09-27,2014-10-01,Standard Class,DP-1300018,Darren Powers,Consumer,NaN,São Paulo,...,OFF-BI-6398,Office Supplies,Binders,"Wilson Jones Hole Reinforcements, Durable",12.060,3,0.0,3.4800,1.134,Medium
50963,38356,CA-2014-WB21850140-41985,2014-12-12,2014-12-12,Same Day,WB-218501404,William Brown,Consumer,92804.0,Anaheim,...,OFF-AP-4239,Office Supplies,Appliances,Fellowes 8 Outlet Superior Workstation Surge P...,83.420,2,0.0,24.1918,17.720,Critical
51017,10091,US-2012-KT1646518-41017,2012-04-18,2012-04-24,Standard Class,KT-1646518,Kean Takahito,Consumer,NaN,Araranguá,...,TEC-AC-4151,Technology,Accessories,"Enermax Flash Drive, Bluetooth",22.144,2,0.6,-31.5760,1.083,Low
51129,37507,CA-2015-YS21880140-42235,2015-08-19,2015-08-26,Standard Class,YS-218801404,Yana Sorensen,Corporate,98103.0,Seattle,...,OFF-ST-5076,Office Supplies,Storage,Letter Size Cart,1000.020,7,0.0,290.0058,63.200,Medium

In [ ]:
df2=data[data.duplicated(subset=['Customer ID','City'])]

In [ ]:
df2

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
8,40099,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,FUR-BO-5957,Furniture,Bookcases,"Sauder Facets Collection Library, Sky Alder Fi...",341.960,2,0.0,54.7136,25.270,High
10,36259,CA-2012-AB10015140-40974,2012-03-06,2012-03-07,First Class,AB-100151404,Aaron Bergman,Consumer,98103.0,Seattle,...,OFF-AR-5309,Office Supplies,Art,Newell 330,17.940,3,0.0,4.6644,4.290,High
21,36260,CA-2012-AB10015140-40974,2012-03-06,2012-03-07,First Class,AB-100151404,Aaron Bergman,Consumer,98103.0,Seattle,...,OFF-ST-3744,Office Supplies,Storage,"Carina 42""Hx23 3/4""W Media Storage Unit",242.940,3,0.0,4.8588,1.280,High
34,40976,CA-2013-AH10030140-41635,2013-12-27,2013-12-31,Standard Class,AH-100301404,Aaron Hawkins,Corporate,94122.0,San Francisco,...,OFF-ST-4291,Office Supplies,Storage,Fellowes Super Stor/Drawer Files,323.100,2,0.0,61.3890,26.700,Medium
50,37425,US-2012-AH10030140-41206,2012-10-24,2012-10-27,First Class,AH-100301404,Aaron Hawkins,Corporate,94109.0,San Francisco,...,OFF-BI-4372,Office Supplies,Binders,GBC VeloBind Cover Sets,49.408,4,0.2,18.5280,2.840,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51280,35112,CA-2014-ZD21925140-41829,2014-07-09,2014-07-09,Same Day,ZD-219251408,Zuschuss Donatelli,Consumer,32216.0,Jacksonville,...,OFF-PA-6474,Office Supplies,Paper,Xerox 1921,15.984,2,0.2,4.9950,2.010,Medium
51284,9922,MX-2013-KM1637593-41636,2013-12-28,2013-12-31,First Class,KM-1637593,Katherine Murray,Home Office,NaN,Managua,...,OFF-PA-5876,Office Supplies,Paper,"SanDisk Message Books, 8.5 x 11",18.640,1,0.0,8.0000,1.010,Medium
51285,29002,IN-2015-KE1642066-42174,2015-06-19,2015-06-19,Same Day,KE-1642066,Katrina Edelman,Corporate,NaN,Kure,...,OFF-FA-3072,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,1.010,Medium
51287,31315,CA-2012-ZD21925140-41147,2012-08-26,2012-08-31,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,OFF-AR-5321,Office Supplies,Art,Newell 341,8.560,2,0.0,2.4824,1.580,High
51288,9596,MX-2013-RB1979518-41322,2013-02-17,2013-02-21,Standard Class,RB-1979518,Ross Baird,Home Office,NaN,Valinhos,...,OFF-BI-2919,Office Supplies,Binders,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,1.003,Medium

In [ ]:
data.drop_duplicates(keep='first',inplace=True)

In [ ]:
data_6 = { 'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'Eve', 'Alice'],
        'Age': [24, 27, 22, 24, 29, 24],
      'City': ['New York', 'Los Angeles', 'Chicago', 'New York', 'Chicago', 'New York'] }
df6=pd.DataFrame(data_6)

In [ ]:
df6

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    Alice   24     New York
4      Eve   29      Chicago
5    Alice   24     New York

In [ ]:
df6.duplicated()

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [ ]:
df6.drop_duplicates()

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
4      Eve   29      Chicago

In [ ]:
df_f=df6.drop_duplicates(keep='first')
df_f
# delete duplicate items and keep first item

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
4      Eve   29      Chicago

In [ ]:
df_l=df6.drop_duplicates(keep='last')
# delete duplicate items and keep last item

In [ ]:
df_l

      Name  Age         City
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
4      Eve   29      Chicago
5    Alice   24     New York

In [ ]:
df_=df6.drop_duplicates(keep=False)
df_
# delete all duplicated items

      Name  Age         City
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
4      Eve   29      Chicago

## **convert data type**

In [ ]:
data.dtypes

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Postal Code              float64
City                      object
State                     object
Country                   object
Region                    object
Market                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
Shipping Cost            float64
Order Priority            object
dtype: object

In [ ]:
data['Postal Code']=data['Postal Code'].astype(str)
# covert a data type to another
# here convert float into str

In [ ]:
data.dtypes

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Postal Code               object
City                      object
State                     object
Country                   object
Region                    object
Market                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
Shipping Cost            float64
Order Priority            object
dtype: object

## **feature engineering**

In [ ]:
data.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Postal Code', 'City',
       'State', 'Country', 'Region', 'Market', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority'],
      dtype='object')

In [ ]:
data[['Sales','Quantity']]

          Sales  Quantity
0       221.980         2
1      3709.395         9
2      5175.171         9
3      2892.510         5
4      2832.960         8
...         ...       ...
51285    65.100         5
51286    16.720         5
51287     8.560         2
51288    13.440         2
51289    61.380         3

[51290 rows x 2 columns]

In [ ]:
data['Total_Order_Value']=data['Sales']*data['Quantity']
# add a new column(feature)into a dataset

In [ ]:
data

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Total_Order_Value
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,Technology,Phones,Samsung Convoy 3,221.980,2,0.0,62.1544,40.770,High,443.960
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,nan,Wollongong,...,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.630,Critical,33384.555
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,nan,Brisbane,...,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.490,Medium,46576.539
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,nan,Berlin,...,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.160,Medium,14462.550
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,nan,Dakar,...,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.040,Critical,22663.680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2015-KE1642066-42174,2015-06-19,2015-06-19,Same Day,KE-1642066,Katrina Edelman,Corporate,nan,Kure,...,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,1.010,Medium,325.500
51286,34337,US-2014-ZD21925140-41765,2014-05-06,2014-05-10,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,Furniture,Furnishings,"Eldon Image Series Desk Accessories, Burgundy",16.720,5,0.2,3.3440,1.930,High,83.600
51287,31315,CA-2012-ZD21925140-41147,2012-08-26,2012-08-31,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,Office Supplies,Art,Newell 341,8.560,2,0.0,2.4824,1.580,High,17.120
51288,9596,MX-2013-RB1979518-41322,2013-02-17,2013-02-21,Standard Class,RB-1979518,Ross Baird,Home Office,nan,Valinhos,...,Office Supplies,Binders,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,1.003,Medium,26.880
51289,6147,MX-2013-MC1810093-41416,2013-05-22,2013-05-26,Second Class,MC-1810093,Mick Crebagga,Consumer,nan,Tipitapa,...,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,1.002,High,184.140

In [ ]:
# Q) Create a feature that calculate the profit margin as a percentage of the total sales?
data['Profit Margin']=(data['Profit']/data['Total_Order_Value']*100)

In [ ]:
data

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Total_Order_Value,Profit Margin
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,Phones,Samsung Convoy 3,221.980,2,0.0,62.1544,40.770,High,443.960,14.000000
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,nan,Wollongong,...,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.630,Critical,33384.555,-0.864966
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,nan,Brisbane,...,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.490,Medium,46576.539,1.975181
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,nan,Berlin,...,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.160,Medium,14462.550,-0.667517
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,nan,Dakar,...,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.040,Critical,22663.680,1.374534
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2015-KE1642066-42174,2015-06-19,2015-06-19,Same Day,KE-1642066,Katrina Edelman,Corporate,nan,Kure,...,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,1.010,Medium,325.500,1.382488
51286,34337,US-2014-ZD21925140-41765,2014-05-06,2014-05-10,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,Furnishings,"Eldon Image Series Desk Accessories, Burgundy",16.720,5,0.2,3.3440,1.930,High,83.600,4.000000
51287,31315,CA-2012-ZD21925140-41147,2012-08-26,2012-08-31,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,Art,Newell 341,8.560,2,0.0,2.4824,1.580,High,17.120,14.500000
51288,9596,MX-2013-RB1979518-41322,2013-02-17,2013-02-21,Standard Class,RB-1979518,Ross Baird,Home Office,nan,Valinhos,...,Binders,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,1.003,Medium,26.880,8.928571
51289,6147,MX-2013-MC1810093-41416,2013-05-22,2013-05-26,Second Class,MC-1810093,Mick Crebagga,Consumer,nan,Tipitapa,...,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,1.002,High,184.140,0.977517

In [ ]:
data.drop(columns='Profit Margin',axis=1)
# to delete a column temperarely
# permanantly use-  inplace=True

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Total_Order_Value
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,Technology,Phones,Samsung Convoy 3,221.980,2,0.0,62.1544,40.770,High,443.960
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,nan,Wollongong,...,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.630,Critical,33384.555
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,nan,Brisbane,...,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.490,Medium,46576.539
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,nan,Berlin,...,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.160,Medium,14462.550
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,nan,Dakar,...,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.040,Critical,22663.680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2015-KE1642066-42174,2015-06-19,2015-06-19,Same Day,KE-1642066,Katrina Edelman,Corporate,nan,Kure,...,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,1.010,Medium,325.500
51286,34337,US-2014-ZD21925140-41765,2014-05-06,2014-05-10,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,Furniture,Furnishings,"Eldon Image Series Desk Accessories, Burgundy",16.720,5,0.2,3.3440,1.930,High,83.600
51287,31315,CA-2012-ZD21925140-41147,2012-08-26,2012-08-31,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,Office Supplies,Art,Newell 341,8.560,2,0.0,2.4824,1.580,High,17.120
51288,9596,MX-2013-RB1979518-41322,2013-02-17,2013-02-21,Standard Class,RB-1979518,Ross Baird,Home Office,nan,Valinhos,...,Office Supplies,Binders,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,1.003,Medium,26.880
51289,6147,MX-2013-MC1810093-41416,2013-05-22,2013-05-26,Second Class,MC-1810093,Mick Crebagga,Consumer,nan,Tipitapa,...,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,1.002,High,184.140

In [ ]:
data.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Postal Code', 'City',
       'State', 'Country', 'Region', 'Market', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority', 'Total_Order_Value',
       'Profit Margin'],
      dtype='object')

In [ ]:
# Q) Create a feature that calculates the price of the product after applying the discount.
data['Final_Price']=data['Sales']*1-data['Discount']

In [ ]:
data

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Total_Order_Value,Profit Margin,Final_Price
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,Samsung Convoy 3,221.980,2,0.0,62.1544,40.770,High,443.960,14.000000,221.980
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,nan,Wollongong,...,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.630,Critical,33384.555,-0.864966,3709.295
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,nan,Brisbane,...,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.490,Medium,46576.539,1.975181,5175.071
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,nan,Berlin,...,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.160,Medium,14462.550,-0.667517,2892.410
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,nan,Dakar,...,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.040,Critical,22663.680,1.374534,2832.960
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2015-KE1642066-42174,2015-06-19,2015-06-19,Same Day,KE-1642066,Katrina Edelman,Corporate,nan,Kure,...,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,1.010,Medium,325.500,1.382488,65.100
51286,34337,US-2014-ZD21925140-41765,2014-05-06,2014-05-10,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,"Eldon Image Series Desk Accessories, Burgundy",16.720,5,0.2,3.3440,1.930,High,83.600,4.000000,16.520
51287,31315,CA-2012-ZD21925140-41147,2012-08-26,2012-08-31,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,Newell 341,8.560,2,0.0,2.4824,1.580,High,17.120,14.500000,8.560
51288,9596,MX-2013-RB1979518-41322,2013-02-17,2013-02-21,Standard Class,RB-1979518,Ross Baird,Home Office,nan,Valinhos,...,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,1.003,Medium,26.880,8.928571,13.440
51289,6147,MX-2013-MC1810093-41416,2013-05-22,2013-05-26,Second Class,MC-1810093,Mick Crebagga,Consumer,nan,Tipitapa,...,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,1.002,High,184.140,0.977517,61.380

In [ ]:
# Q) create a feature that represents the shipping cost per unit sold
data['Cost_1unit']=data['Shipping Cost']/data['Quantity']

In [ ]:
data

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Total_Order_Value,Profit Margin,Final_Price,Cost_1unit
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,221.980,2,0.0,62.1544,40.770,High,443.960,14.000000,221.980,20.385000
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,nan,Wollongong,...,3709.395,9,0.1,-288.7650,923.630,Critical,33384.555,-0.864966,3709.295,102.625556
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,nan,Brisbane,...,5175.171,9,0.1,919.9710,915.490,Medium,46576.539,1.975181,5175.071,101.721111
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,nan,Berlin,...,2892.510,5,0.1,-96.5400,910.160,Medium,14462.550,-0.667517,2892.410,182.032000
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,nan,Dakar,...,2832.960,8,0.0,311.5200,903.040,Critical,22663.680,1.374534,2832.960,112.880000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2015-KE1642066-42174,2015-06-19,2015-06-19,Same Day,KE-1642066,Katrina Edelman,Corporate,nan,Kure,...,65.100,5,0.0,4.5000,1.010,Medium,325.500,1.382488,65.100,0.202000
51286,34337,US-2014-ZD21925140-41765,2014-05-06,2014-05-10,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,16.720,5,0.2,3.3440,1.930,High,83.600,4.000000,16.520,0.386000
51287,31315,CA-2012-ZD21925140-41147,2012-08-26,2012-08-31,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,8.560,2,0.0,2.4824,1.580,High,17.120,14.500000,8.560,0.790000
51288,9596,MX-2013-RB1979518-41322,2013-02-17,2013-02-21,Standard Class,RB-1979518,Ross Baird,Home Office,nan,Valinhos,...,13.440,2,0.0,2.4000,1.003,Medium,26.880,8.928571,13.440,0.501500
51289,6147,MX-2013-MC1810093-41416,2013-05-22,2013-05-26,Second Class,MC-1810093,Mick Crebagga,Consumer,nan,Tipitapa,...,61.380,3,0.0,1.8000,1.002,High,184.140,0.977517,61.380,0.334000

## **extracting date and time components**
from date time object

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 28 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Row ID             51290 non-null  int64
 1   Order ID           51290 non-null  object
 2   Order Date         51290 non-null  datetime64[ns]
 3   Ship Date          51290 non-null  datetime64[ns]
 4   Ship Mode          51290 non-null  object
 5   Customer ID        51290 non-null  object
 6   Customer Name      51290 non-null  object
 7   Segment            51290 non-null  object
 8   Postal Code        51290 non-null  object
 9   City               51290 non-null  object
 10  State              51290 non-null  object
 11  Country            51290 non-null  object
 12  Region             51290 non-null  object
 13  Market             51290 non-null  object
 14  Product ID         51290 non-null  object
 15  Category           51290 non-null  object
 16  Sub-Category       51290 non-null  object
 17  Product Name       51290 non-null  object
 18  Sales              51290 non-null  float64
 19  Quantity           51290 non-null  int64
 20  Discount           51290 non-null  float64
 21  Profit             51290 non-null  float64
 22  Shipping Cost      51290 non-null  float64
 23  Order Priority     51290 non-null  object
 24  Total_Order_Value  51290 non-null  float64
 25  Profit Margin      51290 non-null  float64
 26  Final_Price        51290 non-null  float64
 27  Cost_1unit         51290 non-null  float64
dtypes: datetime64[ns](2), float64(8), int64(2), object(16)
memory usage: 11.0+ MB

In [ ]:
data['order_year']=data['Order Date'].dt.year
# to extract year from 'order date' using datetime module like 2014, 2012,...

In [ ]:
data.head()
# 5 row is default

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Quantity,Discount,Profit,Shipping Cost,Order Priority,Total_Order_Value,Profit Margin,Final_Price,Cost_1unit,order_year
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,2,0.0,62.1544,40.77,High,443.960,14.000000,221.980,20.385000,2014
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,nan,Wollongong,...,9,0.1,-288.7650,923.63,Critical,33384.555,-0.864966,3709.295,102.625556,2014
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,nan,Brisbane,...,9,0.1,919.9710,915.49,Medium,46576.539,1.975181,5175.071,101.721111,2014
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,nan,Berlin,...,5,0.1,-96.5400,910.16,Medium,14462.550,-0.667517,2892.410,182.032000,2014
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,nan,Dakar,...,8,0.0,311.5200,903.04,Critical,22663.680,1.374534,2832.960,112.880000,2014

In [ ]:
data['order month']=data['Order Date'].dt.month
data.head()
# to extract month in order date using datetime module like 1,2,6,9...

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Discount,Profit,Shipping Cost,Order Priority,Total_Order_Value,Profit Margin,Final_Price,Cost_1unit,order_year,order month
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,0.0,62.1544,40.77,High,443.960,14.000000,221.980,20.385000,2014,11
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,nan,Wollongong,...,0.1,-288.7650,923.63,Critical,33384.555,-0.864966,3709.295,102.625556,2014,2
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,nan,Brisbane,...,0.1,919.9710,915.49,Medium,46576.539,1.975181,5175.071,101.721111,2014,10
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,nan,Berlin,...,0.1,-96.5400,910.16,Medium,14462.550,-0.667517,2892.410,182.032000,2014,1
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,nan,Dakar,...,0.0,311.5200,903.04,Critical,22663.680,1.374534,2832.960,112.880000,2014,11

In [ ]:
data['order month']=data['Order Date'].dt.month_name()
data.head()
# to extract month name in date format using datetime module like january, february etc..

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Discount,Profit,Shipping Cost,Order Priority,Total_Order_Value,Profit Margin,Final_Price,Cost_1unit,order_year,order month
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,0.0,62.1544,40.77,High,443.960,14.000000,221.980,20.385000,2014,November
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,nan,Wollongong,...,0.1,-288.7650,923.63,Critical,33384.555,-0.864966,3709.295,102.625556,2014,February
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,nan,Brisbane,...,0.1,919.9710,915.49,Medium,46576.539,1.975181,5175.071,101.721111,2014,October
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,nan,Berlin,...,0.1,-96.5400,910.16,Medium,14462.550,-0.667517,2892.410,182.032000,2014,January
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,nan,Dakar,...,0.0,311.5200,903.04,Critical,22663.680,1.374534,2832.960,112.880000,2014,November

In [ ]:
data['Order day']=data['Order Date'].dt.day
# extract day from 'order date' using datetime module like 1,2,3,4,5,6,7
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Profit,Shipping Cost,Order Priority,Total_Order_Value,Profit Margin,Final_Price,Cost_1unit,order_year,order month,Order day
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,62.1544,40.77,High,443.960,14.000000,221.980,20.385000,2014,November,11
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,nan,Wollongong,...,-288.7650,923.63,Critical,33384.555,-0.864966,3709.295,102.625556,2014,February,5
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,nan,Brisbane,...,919.9710,915.49,Medium,46576.539,1.975181,5175.071,101.721111,2014,October,17
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,nan,Berlin,...,-96.5400,910.16,Medium,14462.550,-0.667517,2892.410,182.032000,2014,January,28
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,nan,Dakar,...,311.5200,903.04,Critical,22663.680,1.374534,2832.960,112.880000,2014,November,5

In [ ]:
data['order day']=data['Order Date'].dt.day_name()
# extract day name from 'order date' like monday, tuesday.....
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Shipping Cost,Order Priority,Total_Order_Value,Profit Margin,Final_Price,Cost_1unit,order_year,order month,Order day,order day
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,40.77,High,443.960,14.000000,221.980,20.385000,2014,November,11,Tuesday
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,nan,Wollongong,...,923.63,Critical,33384.555,-0.864966,3709.295,102.625556,2014,February,5,Wednesday
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,nan,Brisbane,...,915.49,Medium,46576.539,1.975181,5175.071,101.721111,2014,October,17,Friday
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,nan,Berlin,...,910.16,Medium,14462.550,-0.667517,2892.410,182.032000,2014,January,28,Tuesday
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,nan,Dakar,...,903.04,Critical,22663.680,1.374534,2832.960,112.880000,2014,November,5,Wednesday

In [ ]:
data['Ship_year']=data['Ship Date'].dt.year
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Order Priority,Total_Order_Value,Profit Margin,Final_Price,Cost_1unit,order_year,order month,Order day,order day,Ship_year
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,High,443.960,14.000000,221.980,20.385000,2014,November,11,Tuesday,2014
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,nan,Wollongong,...,Critical,33384.555,-0.864966,3709.295,102.625556,2014,February,5,Wednesday,2014
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,nan,Brisbane,...,Medium,46576.539,1.975181,5175.071,101.721111,2014,October,17,Friday,2014
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,nan,Berlin,...,Medium,14462.550,-0.667517,2892.410,182.032000,2014,January,28,Tuesday,2014
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,nan,Dakar,...,Critical,22663.680,1.374534,2832.960,112.880000,2014,November,5,Wednesday,2014

In [ ]:
data['Ship_month']=data['Ship Date'].dt.month
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Total_Order_Value,Profit Margin,Final_Price,Cost_1unit,order_year,order month,Order day,order day,Ship_year,Ship_month
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,443.960,14.000000,221.980,20.385000,2014,November,11,Tuesday,2014,11
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,nan,Wollongong,...,33384.555,-0.864966,3709.295,102.625556,2014,February,5,Wednesday,2014,2
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,nan,Brisbane,...,46576.539,1.975181,5175.071,101.721111,2014,October,17,Friday,2014,10
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,nan,Berlin,...,14462.550,-0.667517,2892.410,182.032000,2014,January,28,Tuesday,2014,1
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,nan,Dakar,...,22663.680,1.374534,2832.960,112.880000,2014,November,5,Wednesday,2014,11

In [ ]:
data['Ship_month_name']=data['Ship Date'].dt.month_name()
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Profit Margin,Final_Price,Cost_1unit,order_year,order month,Order day,order day,Ship_year,Ship_month,Ship_month_name
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,14.000000,221.980,20.385000,2014,November,11,Tuesday,2014,11,November
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,nan,Wollongong,...,-0.864966,3709.295,102.625556,2014,February,5,Wednesday,2014,2,February
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,nan,Brisbane,...,1.975181,5175.071,101.721111,2014,October,17,Friday,2014,10,October
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,nan,Berlin,...,-0.667517,2892.410,182.032000,2014,January,28,Tuesday,2014,1,January
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,nan,Dakar,...,1.374534,2832.960,112.880000,2014,November,5,Wednesday,2014,11,November

In [ ]:
data['Ship_day']=data['Ship Date'].dt.day
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Final_Price,Cost_1unit,order_year,order month,Order day,order day,Ship_year,Ship_month,Ship_month_name,Ship_day
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,221.980,20.385000,2014,November,11,Tuesday,2014,11,November,13
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,nan,Wollongong,...,3709.295,102.625556,2014,February,5,Wednesday,2014,2,February,7
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,nan,Brisbane,...,5175.071,101.721111,2014,October,17,Friday,2014,10,October,18
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,nan,Berlin,...,2892.410,182.032000,2014,January,28,Tuesday,2014,1,January,30
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,nan,Dakar,...,2832.960,112.880000,2014,November,5,Wednesday,2014,11,November,6

In [ ]:
data['Ship_day_name']=data['Ship Date'].dt.day_name()
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Cost_1unit,order_year,order month,Order day,order day,Ship_year,Ship_month,Ship_month_name,Ship_day,Ship_day_name
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,20.385000,2014,November,11,Tuesday,2014,11,November,13,Thursday
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,nan,Wollongong,...,102.625556,2014,February,5,Wednesday,2014,2,February,7,Friday
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,nan,Brisbane,...,101.721111,2014,October,17,Friday,2014,10,October,18,Saturday
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,nan,Berlin,...,182.032000,2014,January,28,Tuesday,2014,1,January,30,Thursday
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,nan,Dakar,...,112.880000,2014,November,5,Wednesday,2014,11,November,6,Thursday

In [ ]:
# Q) create a new column for the order delivery time difference b/w ship date and order date
data['Order_Delivery_Time']=data['Ship Date']-data['Order Date']
data

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,order_year,order month,Order day,order day,Ship_year,Ship_month,Ship_month_name,Ship_day,Ship_day_name,Order_Delivery_Time
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,2014,November,11,Tuesday,2014,11,November,13,Thursday,2 days
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,nan,Wollongong,...,2014,February,5,Wednesday,2014,2,February,7,Friday,2 days
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,nan,Brisbane,...,2014,October,17,Friday,2014,10,October,18,Saturday,1 days
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,nan,Berlin,...,2014,January,28,Tuesday,2014,1,January,30,Thursday,2 days
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,nan,Dakar,...,2014,November,5,Wednesday,2014,11,November,6,Thursday,1 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2015-KE1642066-42174,2015-06-19,2015-06-19,Same Day,KE-1642066,Katrina Edelman,Corporate,nan,Kure,...,2015,June,19,Friday,2015,6,June,19,Friday,0 days
51286,34337,US-2014-ZD21925140-41765,2014-05-06,2014-05-10,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,2014,May,6,Tuesday,2014,5,May,10,Saturday,4 days
51287,31315,CA-2012-ZD21925140-41147,2012-08-26,2012-08-31,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,2012,August,26,Sunday,2012,8,August,31,Friday,5 days
51288,9596,MX-2013-RB1979518-41322,2013-02-17,2013-02-21,Standard Class,RB-1979518,Ross Baird,Home Office,nan,Valinhos,...,2013,February,17,Sunday,2013,2,February,21,Thursday,4 days
51289,6147,MX-2013-MC1810093-41416,2013-05-22,2013-05-26,Second Class,MC-1810093,Mick Crebagga,Consumer,nan,Tipitapa,...,2013,May,22,Wednesday,2013,5,May,26,Sunday,4 days

**Display today's date**

In [ ]:
import datetime
print(datetime.datetime.now())

2024-09-01 13:27:43.268946

In [ ]:
# Q) Create a feature that calculates the age of an order in days from the order date to today's date
data['Order_ age']=(datetime.datetime.now()-data['Order Date']).dt.days
data

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,order month,Order day,order day,Ship_year,Ship_month,Ship_month_name,Ship_day,Ship_day_name,Order_Delivery_Time,Order_ age
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,November,11,Tuesday,2014,11,November,13,Thursday,2 days,3582
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,nan,Wollongong,...,February,5,Wednesday,2014,2,February,7,Friday,2 days,3861
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,nan,Brisbane,...,October,17,Friday,2014,10,October,18,Saturday,1 days,3607
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,nan,Berlin,...,January,28,Tuesday,2014,1,January,30,Thursday,2 days,3869
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,nan,Dakar,...,November,5,Wednesday,2014,11,November,6,Thursday,1 days,3588
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,29002,IN-2015-KE1642066-42174,2015-06-19,2015-06-19,Same Day,KE-1642066,Katrina Edelman,Corporate,nan,Kure,...,June,19,Friday,2015,6,June,19,Friday,0 days,3362
51286,34337,US-2014-ZD21925140-41765,2014-05-06,2014-05-10,Standard Class,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,May,6,Tuesday,2014,5,May,10,Saturday,4 days,3771
51287,31315,CA-2012-ZD21925140-41147,2012-08-26,2012-08-31,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,August,26,Sunday,2012,8,August,31,Friday,5 days,4389
51288,9596,MX-2013-RB1979518-41322,2013-02-17,2013-02-21,Standard Class,RB-1979518,Ross Baird,Home Office,nan,Valinhos,...,February,17,Sunday,2013,2,February,21,Thursday,4 days,4214
51289,6147,MX-2013-MC1810093-41416,2013-05-22,2013-05-26,Second Class,MC-1810093,Mick Crebagga,Consumer,nan,Tipitapa,...,May,22,Wednesday,2013,5,May,26,Sunday,4 days,4120

In [ ]:
# Q) average shipping delay for orders placed in december
december_orders=data[data['Order Date'].dt.month==12]
december_orders

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,order month,Order day,order day,Ship_year,Ship_month,Ship_month_name,Ship_day,Ship_day_name,Order_Delivery_Time,Order_ age
12,45794,SA-2012-MM7260110-41269,2012-12-26,2012-12-28,Second Class,MM-7260110,Magdelene Morse,Consumer,nan,Jizan,...,December,26,Wednesday,2012,12,December,28,Friday,2 days,4267
19,49463,TZ-2015-RH9555129-42343,2015-12-05,2015-12-07,Second Class,RH-9555129,Ritsa Hightower,Consumer,nan,Uvinza,...,December,5,Saturday,2015,12,December,7,Monday,2 days,3193
26,30191,IN-2012-PB19210127-41259,2012-12-16,2012-12-19,First Class,PB-19210127,Phillip Breyer,Corporate,nan,Taipei,...,December,16,Sunday,2012,12,December,19,Wednesday,3 days,4277
30,220,US-2012-RR1952536-41270,2012-12-27,2012-12-29,Second Class,RR-1952536,Rick Reed,Corporate,nan,Santo Domingo,...,December,27,Thursday,2012,12,December,29,Saturday,2 days,4266
32,40977,CA-2013-AH10030140-41635,2013-12-27,2013-12-31,Standard Class,AH-100301404,Aaron Hawkins,Corporate,94122.0,San Francisco,...,December,27,Friday,2013,12,December,31,Tuesday,4 days,3901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51250,8362,MX-2015-BG1169518-42360,2015-12-22,2015-12-24,First Class,BG-1169518,Brooke Gillingham,Corporate,nan,Ibirité,...,December,22,Tuesday,2015,12,December,24,Thursday,2 days,3176
51254,43851,RS-2015-DP3000108-42355,2015-12-17,2015-12-20,Second Class,DP-3000108,Darren Powers,Consumer,nan,Kaluga,...,December,17,Thursday,2015,12,December,20,Sunday,3 days,3181
51263,6367,MX-2012-BP1123082-41264,2012-12-21,2012-12-25,Standard Class,BP-1123082,Benjamin Patterson,Consumer,nan,Toluca,...,December,21,Friday,2012,12,December,25,Tuesday,4 days,4272
51278,10410,ES-2012-LR1703548-41245,2012-12-02,2012-12-02,Same Day,LR-1703548,Lisa Ryan,Corporate,nan,Hamburg,...,December,2,Sunday,2012,12,December,2,Sunday,0 days,4291
51284,9922,MX-2013-KM1637593-41636,2013-12-28,2013-12-31,First Class,KM-1637593,Katherine Murray,Home Office,nan,Managua,...,December,28,Saturday,2013,12,December,31,Tuesday,3 days,3900

In [ ]:
avg_shipping_delay=december_orders['Order_Delivery_Time'].mean()
avg_shipping_delay

Timedelta('3 days 22:53:29.333546428')

## **replace**

In [ ]:
# Q) replace 'standard class' value in 'ship mode' column with 'std'
data['Ship Mode']=data['Ship Mode'].replace('Standard Class','std')

In [ ]:
data['Ship Mode'].unique()

array(['First Class', 'Second Class', 'Same Day', 'std'], dtype=object)

In [ ]:
# Q) replace 'low' value in 'order priority' column with 'standard'
data['Order Priority'].unique()

array(['High', 'Critical', 'Medium', 'Low'], dtype=object)

In [ ]:
data['Order Priority']=data['Order Priority'].replace('Low','standard')

In [ ]:
data['Order Priority'].unique()

array(['High', 'Critical', 'Medium', 'standard'], dtype=object)

## **filter & sort**

In [ ]:
segment_consumer=data[data['Segment']=='Consumer']
segment_consumer.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,order month,Order day,order day,Ship_year,Ship_month,Ship_month_name,Ship_day,Ship_day_name,Order_Delivery_Time,Order_ age
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,November,11,Tuesday,2014,11,November,13,Thursday,2 days,3582
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,nan,Brisbane,...,October,17,Friday,2014,10,October,18,Saturday,1 days,3607
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,nan,Dakar,...,November,5,Wednesday,2014,11,November,6,Thursday,1 days,3588
6,30570,IN-2012-TS2134092-41219,2012-11-06,2012-11-08,First Class,TS-2134092,Toby Swindell,Consumer,nan,Porirua,...,November,6,Tuesday,2012,11,November,8,Thursday,2 days,4317
7,31192,IN-2013-MB1808592-41378,2013-04-14,2013-04-18,std,MB-1808592,Mick Brown,Consumer,nan,Hamilton,...,April,14,Sunday,2013,4,April,18,Thursday,4 days,4158

In [ ]:
# Q) filter the rows where profit lessthan zero
data[(data['Profit']<0)]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,order month,Order day,order day,Ship_year,Ship_month,Ship_month_name,Ship_day,Ship_day_name,Order_Delivery_Time,Order_ age
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,nan,Wollongong,...,February,5,Wednesday,2014,2,February,7,Friday,2 days,3861
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,nan,Berlin,...,January,28,Tuesday,2014,1,January,30,Thursday,2 days,3869
16,39519,CA-2012-AB10015140-40958,2012-02-19,2012-02-25,std,AB-100151402,Aaron Bergman,Consumer,76017.0,Arlington,...,February,19,Sunday,2012,2,February,25,Saturday,6 days,4578
30,220,US-2012-RR1952536-41270,2012-12-27,2012-12-29,Second Class,RR-1952536,Rick Reed,Corporate,nan,Santo Domingo,...,December,27,Thursday,2012,12,December,29,Saturday,2 days,4266
40,21316,ID-2014-JB1600059-41873,2014-08-22,2014-08-26,std,JB-1600059,Joy Bell-,Consumer,nan,Mataram,...,August,22,Friday,2014,8,August,26,Tuesday,4 days,3663
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51260,35398,US-2015-ZC21910140-42175,2015-06-20,2015-06-24,std,ZC-219101402,Zuschuss Carroll,Consumer,77095.0,Houston,...,June,20,Saturday,2015,6,June,24,Wednesday,4 days,3361
51266,27081,ID-2013-EK13795102-41496,2013-08-10,2013-08-11,First Class,EK-13795102,Eileen Kiefer,Home Office,nan,Pasig,...,August,10,Saturday,2013,8,August,11,Sunday,1 days,4040
51275,46231,ZA-2012-AS285147-40988,2012-03-20,2012-03-25,std,AS-285147,Alejandro Savely,Corporate,nan,Harare,...,March,20,Tuesday,2012,3,March,25,Sunday,5 days,4548
51277,46582,TU-2015-KF6285134-42337,2015-11-29,2015-11-30,First Class,KF-6285134,Karen Ferguson,Home Office,nan,Midyat,...,November,29,Sunday,2015,11,November,30,Monday,1 days,3199
51279,43818,NI-2012-PO886595-41159,2012-09-07,2012-09-09,Second Class,PO-886595,Patrick O'Donnell,Consumer,nan,Lagos,...,September,7,Friday,2012,9,September,9,Sunday,2 days,4377

In [ ]:
# Q) filter rows where profit is negative and the quantity is greater than 10
filter_rows=data[(data['Profit']<0)&(data['Quantity']>10)]
filter_rows

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,order month,Order day,order day,Ship_year,Ship_month,Ship_month_name,Ship_day,Ship_day_name,Order_Delivery_Time,Order_ age
109,11743,IT-2014-VM2168591-41711,2014-03-13,2014-03-13,Same Day,VM-2168591,Valerie Mitchum,Home Office,nan,Bergen op Zoom,...,March,13,Thursday,2014,3,March,13,Thursday,0 days,3825
289,43395,TU-2013-SF10200134-41417,2013-05-23,2013-05-26,First Class,SF-10200134,Sarah Foster,Consumer,nan,Izmir,...,May,23,Thursday,2013,5,May,26,Sunday,3 days,4119
298,16456,IT-2013-JD16060120-41515,2013-08-29,2013-09-01,First Class,JD-16060120,Julia Dunbar,Consumer,nan,Santander,...,August,29,Thursday,2013,9,September,1,Sunday,3 days,4021
362,29513,ID-2014-SN2056097-41896,2014-09-14,2014-09-14,Same Day,SN-2056097,Skye Norling,Home Office,nan,Lahore,...,September,14,Sunday,2014,9,September,14,Sunday,0 days,3640
368,29552,IN-2015-SV2078559-42110,2015-04-16,2015-04-18,Second Class,SV-2078559,Stewart Visinsky,Consumer,nan,Medan,...,April,16,Thursday,2015,4,April,18,Saturday,2 days,3426
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46367,8903,US-2014-TB2119018-41727,2014-03-29,2014-03-31,First Class,TB-2119018,Thomas Brumley,Home Office,nan,Salvador,...,March,29,Saturday,2014,3,March,31,Monday,2 days,3809
48243,32342,CA-2015-SN20710140-42290,2015-10-13,2015-10-17,std,SN-207101402,Steve Nguyen,Home Office,61107.0,Rockford,...,October,13,Tuesday,2015,10,October,17,Saturday,4 days,3246
49090,19360,IT-2012-MC17590124-41055,2012-05-26,2012-05-29,First Class,MC-17590124,Matt Collister,Corporate,nan,Stockholm,...,May,26,Saturday,2012,5,May,29,Tuesday,3 days,4481
50328,5131,US-2015-SS208755-42204,2015-07-19,2015-07-23,std,SS-208755,Sung Shariari,Consumer,nan,Buenos Aires,...,July,19,Sunday,2015,7,July,23,Thursday,4 days,3332
50773,40318,CA-2013-VP21760140-41593,2013-11-15,2013-11-20,std,VP-217601406,Victoria Pisteka,Corporate,43615.0,Toledo,...,November,15,Friday,2013,11,November,20,Wednesday,5 days,3943

In [ ]:
# Q) calculate the average sales of these filtered rows
filter_rows['Sales'].mean()

650.2714193333333

In [ ]:
# Q) modify the 'order priority' column to label all orders with a 'profit below zero as "urgent"'?
data.loc[data['Profit']<0,'Order Priority']='Urgent'

In [ ]:
data['Order Priority'].unique()

array(['High', 'Urgent', 'Medium', 'Critical', 'standard'], dtype=object)

In [ ]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,order month,Order day,order day,Ship_year,Ship_month,Ship_month_name,Ship_day,Ship_day_name,Order_Delivery_Time,Order_ age
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,November,11,Tuesday,2014,11,November,13,Thursday,2 days,3582
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,nan,Wollongong,...,February,5,Wednesday,2014,2,February,7,Friday,2 days,3861
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,nan,Brisbane,...,October,17,Friday,2014,10,October,18,Saturday,1 days,3607
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,nan,Berlin,...,January,28,Tuesday,2014,1,January,30,Thursday,2 days,3869
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,nan,Dakar,...,November,5,Wednesday,2014,11,November,6,Thursday,1 days,3588

In [ ]:
# Q) how many rows have 'Urgent' as the order priority
data[data['Order Priority']=='Urgent'].shape[0]

12544

In [ ]:
# using len()
len(data[data['Order Priority']=='Urgent'])

12544

In [ ]:
# Q) filter data where category is furniture and profit is greater than 1000
furniture_1000=data[(data['Category']=='Furniture')&(data['Profit']>1000)]
furniture_1000

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,order month,Order day,order day,Ship_year,Ship_month,Ship_month_name,Ship_day,Ship_day_name,Order_Delivery_Time,Order_ age
42,25795,IN-2015-VG2180558-42273,2015-09-26,2015-09-28,Second Class,VG-2180558,Vivek Grady,Corporate,nan,Thiruvananthapuram,...,September,26,Saturday,2015,9,September,28,Monday,2 days,3263
66,16653,IT-2015-DK13090120-42345,2015-12-07,2015-12-08,First Class,DK-13090120,Dave Kipp,Consumer,nan,Seville,...,December,7,Monday,2015,12,December,8,Tuesday,1 days,3191
70,21191,IN-2014-AS1022527-41797,2014-06-07,2014-06-09,First Class,AS-1022527,Alan Schoenberger,Corporate,nan,Jinan,...,June,7,Saturday,2014,6,June,9,Monday,2 days,3739
72,49085,CG-2014-BW106533-41727,2014-03-29,2014-03-31,Second Class,BW-106533,Barry Weirich,Consumer,nan,Kananga,...,March,29,Saturday,2014,3,March,31,Monday,2 days,3809
88,27962,IN-2014-BK1126011-41940,2014-10-28,2014-10-31,First Class,BK-1126011,Berenike Kampe,Consumer,nan,Tongi,...,October,28,Tuesday,2014,10,October,31,Friday,3 days,3596
118,14070,IT-2012-ON1871545-40955,2012-02-16,2012-02-19,Second Class,ON-1871545,Odella Nelson,Corporate,nan,Muret,...,February,16,Thursday,2012,2,February,19,Sunday,3 days,4581
190,24859,IN-2015-JF1519021-42341,2015-12-03,2015-12-07,std,JF-1519021,Jamie Frazer,Consumer,nan,Phnom Penh,...,December,3,Thursday,2015,12,December,7,Monday,4 days,3195
192,15359,ES-2014-JG15160139-41660,2014-01-21,2014-01-24,Second Class,JG-15160139,James Galang,Consumer,nan,Stockton-on-Tees,...,January,21,Tuesday,2014,1,January,24,Friday,3 days,3876
205,15922,ES-2014-RB19570120-41971,2014-11-28,2014-12-04,std,RB-19570120,Rob Beeghly,Consumer,nan,Barakaldo,...,November,28,Friday,2014,12,December,4,Thursday,6 days,3565
243,12449,ES-2015-MS17770139-42275,2015-09-28,2015-10-01,First Class,MS-17770139,Maxwell Schwartz,Consumer,nan,Burnley,...,September,28,Monday,2015,10,October,1,Thursday,3 days,3261
249,50593,EG-2014-MT807038-41675,2014-02-05,2014-02-07,Second Class,MT-807038,Michelle Tran,Home Office,nan,Girga,...,February,5,Wednesday,2014,2,February,7,Friday,2 days,3861
334,21263,IN-2015-MB173057-42179,2015-06-24,2015-06-28,std,MB-173057,Maria Bertelson,Consumer,nan,Sydney,...,June,24,Wednesday,2015,6,June,28,Sunday,4 days,3357
476,20872,IN-2014-FH1427559-41991,2014-12-18,2014-12-25,std,FH-1427559,Frank Hawley,Corporate,nan,Palu,...,December,18,Thursday,2014,12,December,25,Thursday,7 days,3545
628,25242,IN-2012-CD1192027-40979,2012-03-11,2012-03-16,std,CD-1192027,Carlos Daly,Consumer,nan,Shanghai,...,March,11,Sunday,2012,3,March,16,Friday,5 days,4557
639,18760,ES-2014-EG1390045-41644,2014-01-05,2014-01-10,std,EG-1390045,Emily Grady,Consumer,nan,Puteaux,...,January,5,Sunday,2014,1,January,10,Friday,5 days,3892
738,12230,IT-2012-KN16390139-41268,2012-12-25,2012-12-30,std,KN-16390139,Katherine Nockton,Corporate,nan,Blackpool,...,December,25,Tuesday,2012,12,December,30,Sunday,5 days,4268
763,14818,ES-2014-ES14020120-41817,2014-06-27,2014-06-27,Same Day,ES-14020120,Erica Smith,Consumer,nan,Madrid,...,June,27,Friday,2014,6,June,27,Friday,0 days,3719
804,21620,IN-2012-CS1184527-41139,2012-08-18,2012-08-22,std,CS-1184527,Cari Sayre,Corporate,nan,Luoyang,...,August,18,Saturday,2012,8,August,22,Wednesday,4 days,4397
808,25862,IN-2015-DO1343558-42141,2015-05-17,2015-05-22,Second Class,DO-1343558,Denny Ordway,Consumer,nan,Srinagar,...,May,17,Sunday,2015,5,May,22,Friday,5 days,3395
881,28056,IN-2015-TS2150527-42286,2015-10-09,2015-10-13,std,TS-2150527,Tony Sayre,Consumer,nan,Beijing,...,October,9,Friday,2015,10,October,13,Tuesday,4 days,3250
882,22551,IN-2015-MG1814558-42087,2015-03-24,2015-03-30,std,MG-1814558,Mike Gockenbach,Consumer,nan,Bhilwara,...,March,24,Tuesday,2015,3,March,30,Monday,6 days,3449
901,15440,IT-2014-SP2086045-41956,2014-11-13,2014-11-18,std,SP-2086045,Sung Pak,Corporate,nan,Mulhouse,...,November,13,Thursday,2014,11,November,18,Tuesday,5 days,3580
940,50372,RS-2012-GZ4545108-41088,2012-06-28,2012-07-03,std,GZ-4545108,George Zrebassa,Corporate,nan,Blagoveshchensk,...,June,28,Thursday,2012,7,July,3,Tuesday,5 days,4448
1101,24317,IN-2014-CS1184511-41664,2014-01-25,2014-01-30,std,CS-1184511,Cari Sayre,Corporate,nan,Khulna,...,January,25,Saturday,2014,1,January,30,Thursday,5 days,3872
1164,24037,IN-2015-MG1769527-42294,2015-10-17,2015-10-22,std,MG-1769527,Maureen Gnade,Consumer,nan,Qingdao,...,October,17,Saturday,2015,10,October,22,Thursday,5 days,3242
1736,44850,EG-2015-CR258038-42335,2015-11-27,2015-12-03,std,CR-258038,Clay Rozendal,Home Office,nan,Alexandria,...,November,27,Friday,2015,12,December,3,Thursday,6 days,3201
1759,6712,MX-2012-GT1471039-40975,2012-03-07,2012-03-12,std,GT-1471039,Greg Tran,Consumer,nan,San Salvador,...,March,7,Wednesday,2012,3,March,12,Monday,5 days,4561
2436,19657,ES-2014-ML1804045-41972,2014-11-29,2014-12-06,std,ML-1804045,Michelle Lonsdale,Corporate,nan,Paris,...,November,29,Saturday,2014,12,December,6,Saturday,7 days,3564
2531,11004,ES-2015-DL133158-42320,2015-11-12,2015-11-16,std,DL-133158,Delfina Latchford,Consumer,nan,Villach,...,November,12,Thursday,2015,11,November,16,Monday,4 days,3216
2877,24108,IN-2014-YC2189527-41896,2014-09-14,2014-09-21,std,YC-2189527,Yoseph Carroll,Corporate,nan,Xinghua,...,September,14,Sunday,2014,9,September,21,Sunday,7 days,3640
3478,911,MX-2012-AF1087031-41208,2012-10-26,2012-10-30,std,AF-1087031,Art Ferguson,Consumer,nan,Santa Clara,...,October,26,Friday,2012,10,October,30,Tuesday,4 days,4328
6790,50977,UP-2013-PJ9015137-41353,2013-03-20,2013-03-23,First Class,PJ-9015137,Pauline Johnson,Consumer,nan,Dnipropetrovs'k,...,March,20,Wednesday,2013,3,March,23,Saturday,3 days,4183
19310,21850,IN-2012-MC1757527-41157,2012-09-05,2012-09-12,std,MC-1757527,Matt Collins,Consumer,nan,Yancheng,...,September,5,Wednesday,2012,9,September,12,Wednesday,7 days,4379
43945,41038,CA-2013-QJ19255140-41586,2013-11-08,2013-11-12,std,QJ-192551406,Quincy Jones,Corporate,5408.0,Burlington,...,November,8,Friday,2013,11,November,12,Tuesday,4 days,3950

In [ ]:
# Q) filter rows where product name contain word'phone'
data[data['Product Name'].str.contains('Phone')]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,order month,Order day,order day,Ship_year,Ship_month,Ship_month_name,Ship_day,Ship_day_name,Order_Delivery_Time,Order_ age
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,nan,Brisbane,...,October,17,Friday,2014,10,October,18,Saturday,1 days,3607
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,nan,Berlin,...,January,28,Tuesday,2014,1,January,30,Thursday,2 days,3869
5,22732,IN-2014-JM156557-41818,2014-06-28,2014-07-01,Second Class,JM-156557,Jim Mitchum,Corporate,nan,Sydney,...,June,28,Saturday,2014,7,July,1,Tuesday,3 days,3718
12,45794,SA-2012-MM7260110-41269,2012-12-26,2012-12-28,Second Class,MM-7260110,Magdelene Morse,Consumer,nan,Jizan,...,December,26,Wednesday,2012,12,December,28,Friday,2 days,4267
24,1570,US-2015-NP1832582-42216,2015-07-31,2015-08-01,First Class,NP-1832582,Naresj Patel,Consumer,nan,Juárez,...,July,31,Friday,2015,8,August,1,Saturday,1 days,3320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50805,31512,CA-2013-VW21775140-41275,2013-01-01,2013-01-08,std,VW-217751406,Victoria Wilson,Corporate,44256.0,Medina,...,January,1,Tuesday,2013,1,January,8,Tuesday,7 days,4261
50858,8089,US-2015-PS1904598-42349,2015-12-11,2015-12-16,std,PS-1904598,Penelope Sewall,Home Office,nan,Panama City,...,December,11,Friday,2015,12,December,16,Wednesday,5 days,3187
50881,43296,PL-2012-DB2910103-41005,2012-04-06,2012-04-08,Second Class,DB-2910103,Daniel Byrd,Home Office,nan,Poznan,...,April,6,Friday,2012,4,April,8,Sunday,2 days,4531
51200,32343,CA-2014-ZC21910140-41707,2014-03-09,2014-03-14,std,ZC-219101408,Zuschuss Carroll,Consumer,33142.0,Miami,...,March,9,Sunday,2014,3,March,14,Friday,5 days,3829
51262,31316,CA-2012-ZD21925140-41147,2012-08-26,2012-08-31,Second Class,ZD-219251404,Zuschuss Donatelli,Consumer,94109.0,San Francisco,...,August,26,Sunday,2012,8,August,31,Friday,5 days,4389

## **sorting**

In [ ]:
data['Sales'].sort_values(ascending=False)

47114    22638.480
49003    17499.950
44248    13999.960
49940    11199.968
25238    10499.970
           ...
24977        0.876
26588        0.852
33493        0.836
45391        0.556
51260        0.444
Name: Sales, Length: 51290, dtype: float64

In [ ]:
data[['Sales','Product Name']].sort_values(by='Sales',ascending=False)

           Sales                                       Product Name
47114  22638.480  Cisco TelePresence System EX90 Videoconferenci...
49003  17499.950              Canon imageCLASS 2200 Advanced Copier
44248  13999.960              Canon imageCLASS 2200 Advanced Copier
49940  11199.968              Canon imageCLASS 2200 Advanced Copier
25238  10499.970              Canon imageCLASS 2200 Advanced Copier
...          ...                                                ...
24977      0.876                                  Acco 3-Hole Punch
26588      0.852                      Avery Round Ring Poly Binders
33493      0.836  Avery Durable Slant Ring Binders With Label Ho...
45391      0.556           Acco Suede Grain Vinyl Round Ring Binder
51260      0.444  Hoover Replacement Belt for Commercial Guardsm...

[51290 rows x 2 columns]

In [ ]:
# Q) sort the dataset first by 'category' in ascending order and then by 'profit' in descending order
data[['Category','Profit']].sort_values(by=['Category','Profit'],ascending=[True,False])

         Category     Profit
334     Furniture  2316.5100
42      Furniture  2097.0300
192     Furniture  2071.4400
118     Furniture  1868.1300
940     Furniture  1622.8800
...           ...        ...
362    Technology -3009.4350
47527  Technology -3399.9800
23110  Technology -3839.9904
6591   Technology -4088.3760
11755  Technology -6599.9780

[51290 rows x 2 columns]

In [ ]:
# Q) how can you sort the dataset by 'quantity' in descending order and then select the top 10 records
data['Quantity'].sort_values(ascending=False).head(10)

7971     14
17405    14
40522    14
15388    14
33134    14
13398    14
17675    14
10107    14
2680     14
31397    14
Name: Quantity, dtype: int64

In [ ]:
# Q) sort the dataset by "order date" in ascending order
data['Order Date'].sort_values(ascending=True)

22950   2012-01-01
43610   2012-01-01
25078   2012-01-01
31870   2012-01-01
31583   2012-01-01
           ...
17379   2015-12-31
42870   2015-12-31
39873   2015-12-31
7908    2015-12-31
39602   2015-12-31
Name: Order Date, Length: 51290, dtype: datetime64[ns]

In [ ]:
# Q) Filter the dataset to include  only rows where the order date is between '2013-01-01' and '2014-12-31'?
data.loc[(data['Order Date']>='2013-01-01')&(data['Order Date']<='2014-12-31')]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,order month,Order day,order day,Ship_year,Ship_month,Ship_month_name,Ship_day,Ship_day_name,Order_Delivery_Time,Order_ age
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,November,11,Tuesday,2014,11,November,13,Thursday,2 days,3582
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,nan,Wollongong,...,February,5,Wednesday,2014,2,February,7,Friday,2 days,3861
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,nan,Brisbane,...,October,17,Friday,2014,10,October,18,Saturday,1 days,3607
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,nan,Berlin,...,January,28,Tuesday,2014,1,January,30,Thursday,2 days,3869
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,nan,Dakar,...,November,5,Wednesday,2014,11,November,6,Thursday,1 days,3588
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51280,35112,CA-2014-ZD21925140-41829,2014-07-09,2014-07-09,Same Day,ZD-219251408,Zuschuss Donatelli,Consumer,32216.0,Jacksonville,...,July,9,Wednesday,2014,7,July,9,Wednesday,0 days,3707
51284,9922,MX-2013-KM1637593-41636,2013-12-28,2013-12-31,First Class,KM-1637593,Katherine Murray,Home Office,nan,Managua,...,December,28,Saturday,2013,12,December,31,Tuesday,3 days,3900
51286,34337,US-2014-ZD21925140-41765,2014-05-06,2014-05-10,std,ZD-219251408,Zuschuss Donatelli,Consumer,37421.0,Chattanooga,...,May,6,Tuesday,2014,5,May,10,Saturday,4 days,3771
51288,9596,MX-2013-RB1979518-41322,2013-02-17,2013-02-21,std,RB-1979518,Ross Baird,Home Office,nan,Valinhos,...,February,17,Sunday,2013,2,February,21,Thursday,4 days,4214
51289,6147,MX-2013-MC1810093-41416,2013-05-22,2013-05-26,Second Class,MC-1810093,Mick Crebagga,Consumer,nan,Tipitapa,...,May,22,Wednesday,2013,5,May,26,Sunday,4 days,4120

In [ ]:
data = { 'Timestamp': ['2024-07-24 14:45:00', '2024-07-25 16:30:00',
                                         '2024-07-26 08:20:00', '2024-07-27 12:15:00'] }
df = pd.DataFrame(data)

In [ ]:
df

             Timestamp
0  2024-07-24 14:45:00
1  2024-07-25 16:30:00
2  2024-07-26 08:20:00
3  2024-07-27 12:15:00

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Timestamp  4 non-null      object
dtypes: object(1)
memory usage: 160.0+ bytes

In [ ]:
df['Timestamp']=pd.to_datetime(df['Timestamp'])
# convert to datetime format
# to_datetime  :- pandas function to convert datetime format
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Timestamp  4 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 160.0 bytes

In [ ]:
df['Timestamp']=(df['Timestamp']).astype('datetime64[ns]')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Timestamp  4 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 160.0 bytes

In [ ]:
df['date']=df['Timestamp'].dt.date
df['year']=df['Timestamp'].dt.year
df['month']=df['Timestamp'].dt.month
df['month_name']=df['Timestamp'].dt.month_name()
df['day']=df['Timestamp'].dt.day
df['day_name']=df['Timestamp'].dt.day_name()

In [ ]:
df['hour']=df['Timestamp'].dt.hour
# to extract hour in time
df['minute']=df['Timestamp'].dt.minute
# to extract minute in time
df['second']=df['Timestamp'].dt.second
# to extract second in time

In [ ]:
df

,Timestamp,date,year,month,month_name,day,day_name,hour,minute,second
0,2024-07-24 14:45:00,2024-07-24,2024,7,July,24,Wednesday,14,45,0
1,2024-07-25 16:30:00,2024-07-25,2024,7,July,25,Thursday,16,30,0
2,2024-07-26 08:20:00,2024-07-26,2024,7,July,26,Friday,8,20,0
3,2024-07-27 12:15:00,2024-07-27,2024,7,July,27,Saturday,12,15,0

**date_range**

To generate a date range in Pandas, you can use the pd.date_range() function. This is useful for creating sequences of dates or for setting up a date index.

You can specify the start date, end date, and frequency of the dates.

Parameters:
start: The start date of the range.
end: The end date of the range.
freq: The frequency of the dates ('D' for daily, 'W' for weekly, 'M' for monthly, etc.).

In [ ]:
ds=pd.date_range(start='2020-01-01',end='2021-01-01')

to create a date column with randomly includes starting and ending date

In [ ]:
ds

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2020-12-23', '2020-12-24', '2020-12-25', '2020-12-26',
               '2020-12-27', '2020-12-28', '2020-12-29', '2020-12-30',
               '2020-12-31', '2021-01-01'],
              dtype='datetime64[ns]', length=367, freq='D')

In [ ]:
ds=pd.date_range(start='2020-01-01',end='2021-01-01',freq='D')
ds

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2020-12-23', '2020-12-24', '2020-12-25', '2020-12-26',
               '2020-12-27', '2020-12-28', '2020-12-29', '2020-12-30',
               '2020-12-31', '2021-01-01'],
              dtype='datetime64[ns]', length=367, freq='D')

In [ ]:
ds=pd.date_range(start='2020-01-01',end='2021-01-01',freq='M')
ds

DatetimeIndex(['2020-01-31', '2020-02-29', '2020-03-31', '2020-04-30',
               '2020-05-31', '2020-06-30', '2020-07-31', '2020-08-31',
               '2020-09-30', '2020-10-31', '2020-11-30', '2020-12-31'],
              dtype='datetime64[ns]', freq='M')

'periods' used for the controlling the frequency

In [ ]:
ds=pd.date_range(start='2020-01-01',end='2021-01-01',periods=10)
ds

DatetimeIndex(['2020-01-01 00:00:00', '2020-02-10 16:00:00',
               '2020-03-22 08:00:00', '2020-05-02 00:00:00',
               '2020-06-11 16:00:00', '2020-07-22 08:00:00',
               '2020-09-01 00:00:00', '2020-10-11 16:00:00',
               '2020-11-21 08:00:00', '2021-01-01 00:00:00'],
              dtype='datetime64[ns]', freq=None)